
SET( G2O_PREFIX_DIR ${PROJECT_BINARY_DIR}/G2O )
SET( G2O_INSTALL_DIR ${G2O_PREFIX_DIR} )
SET( G2O_SOURCE_DIR ${G2O_PREFIX_DIR}/src/G2O )


SET( G2O_ARGS "-DCMAKE_RELEASE_TYPE:string=Release" )
LIST( APPEND G2O_ARGS "-DG2O_BUILD_APPS:string=OFF" )
LIST( APPEND G2O_ARGS "-DG2O_BUILD_EXAMPLES:string=OFF" )

ExternalProject_Add( G2O
										GIT_REPOSITORY https://github.com/RainerKuemmerle/g2o.git
										PREFIX G2O
										CMAKE_CACHE_ARGS    )

set( G2O_ROOT ${G2O_INSTALL_DIR} )

${G2O_CORE_LIBRARY}
${G2O_STUFF_LIBRARY}
${G2O_SOLVER_CSPARSE_EXTENSION}
${G2O_SOLVER_CSPARSE}
${G2O_TYPES_SBA}
${G2O_TYPES_SIM3}
