
SET( PANGOLIN_PREFIX_DIR ${PROJECT_BINARY_DIR}/PANGOLIN )
SET( PANGOLIN_INSTALL_DIR ${PANGOLIN_PREFIX_DIR} )
SET( PANGOLIN_SOURCE_DIR ${PANGOLIN_PREFIX_DIR}/src/PANGOLIN )


ExternalProject_Add( PANGOLIN
										GIT_REPOSITORY https://github.com/stevenlovegrove/Pangolin.git
										PREFIX PANGOLIN
										CMAKE_CACHE_ARGS -DCMAKE_RELEASE_TYPE:string=Release )

set( PANGOLIN_ROOT ${PANGOLIN_INSTALL_DIR} )
